version: '3.8'
services:
  db:
    image: mysql
    container_name: springBootE2.mySql.container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data:
