server:
  error:
    include-stacktrace: on-param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/series?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

loggin:
  level:
    org:
      hibernate:
        SQL: DEBUG

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: false
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
  info:
    env:
      enabled: true